---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

# Job Application Exercises

Job application exercises for the open positions:

* Research Scientists (m/f/d) Biomathematical Modeling (#[7578](https://www.genstat.imise.uni-leipzig.de/sites/www.genstat.imise.uni-leipzig.de/files/files/uploads/7578_2-WissMitarb_EN.pdf)) 
* Technical Assistant (m/f/d) Support for Data Analysis and Biomathematical Modeling (#[7577](https://www.genstat.imise.uni-leipzig.de/sites/www.genstat.imise.uni-leipzig.de/files/files/uploads/7577_1-TechMitarb_EN.pdf)). 

# Generell instructions

Please solve at least one of the two exercises regarding genetic analyses ([**ExeciseGenetics/**](https://github.com/GenStatLeipzig/JobApplicationExercises/tree/main/ExerciseGenetics)) or modelling ([**ExeciseModelling/**](https://github.com/GenStatLeipzig/JobApplicationExercises/tree/main/ExerciseModelling)) using R for your upcoming interview.

The exercises are given both as .Rmd and .pdf files. You are free to use the .Rmd as template. You can also fork the repository and solve the exercise(s) in your own github / R environment. 

For the genetic exercise, no additional packages are required. We recommend the package *deSolve* for the modelling exercise. 

Please send your solutions (e.g. R code, generated output) back per mail to Markus Scholz (markus.scholz@imise.uni-leipzig.de) with reference "Job Application - Solution [Genetics or Modelling or both] - [Name]". The solutions will be part of our application documents. 

Please prepare a short presentation of your code and results for the interview (max. 10 minutes). 
